### ISSUE TITLE
How to perform data loading

### ISSUE THREAD

**Issue by sirfoga** [XGGNet/Domain-generalization-with-task-augmentation-for-MIA#3]
Thanks for your code! I'm trying to reproduce your results but the data loading step is missing. You load scan slices from e.g LIVER/{challenge}.txt which lists "...{challenge}/case{XXX}/image{XXX}.jpg". However this is not the original format of the data. Is this pre-processed already? Which slices do they correspond to? Is there any information regarding data pre-processing?

**Comment by chenxinli001** [comment]
Thank you. You may refer to the details in https://github.com/Au3C2/GVS to pre-process your liver data. The final shape of the data pre-processing should be the selected slices (.jpg) for each case (subject).
